syntax on
set nu rnu
set smartindent
set nowrap
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch hlsearch
set scrolloff=80
set cmdheight=1
set cursorline
set showcmd
set colorcolumn=80
set shm+=I
set laststatus=2

" %f - relative path
" %h - help
" %w - preview
" %m - modified
" %r - readonly
" %= - right align
" %y - filetype
" %l - current line
" %c - column number
" %V - virtual col, not displayed if == %c
" %P - percentage of file progressed

set statusline = 
set statusline+=%f
set statusline+=%h%w
set statusline+=%m
set statusline+=\ %r
set statusline+=%=
set statusline+=\ %y
set statusline+=\ \(
set statusline+=%{&fileencoding?&fileencoding:&encoding}
set statusline+=\[
set statusline+=%{&fileformat}
set statusline+=\]\)
set statusline+=\ %-7.(%l,%c%V%)%P

" 4-space indents
set shiftwidth=4 
" tab key for indentation
set smarttab
" only use space characters
set expandtab
" 8-space tabs, don't use
" tabs and spaces together
set tabstop=8 softtabstop=0

let mapleader = "\<Space>"

nnoremap <Leader>pv :Ex<cr>
noremap <Leader>w <C-w>
map <leader>n :bnext<cr>
map <leader>p :bprevious<cr>
map <leader>d :bdelete<cr>
map <leader>hc :let @/ = ""<cr>

filetype plugin on
set clipboard=unnamedplus

call plug#begin()

Plug 'gruvbox-community/gruvbox'

call plug#end()

set background=dark
colorscheme gruvbox
