theme = "everforest_dark"

# <C-c> to get out of everything
[keys.normal]
"C-c" = ["keep_primary_selection", "collapse_selection"]
[keys.insert]
"C-c" = "normal_mode"
[keys.select]
"C-c" = ["normal_mode", "keep_primary_selection", "collapse_selection"]

# gq to reflow
[keys.select.g]
q = ":reflow"

# <Space>o for file picker in current dir
[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"

[editor]
scrolloff = 10
line-number = "relative"
cursorline = true
continue-comments = true
lsp.display-inlay-hints = true
rulers = [80]

[editor.inline-diagnostics]
cursor-line = "hint"
